Update OnePlus 6-series instructions for Android 14
crdroidandroid/install_docs pull request #79
Opened 2024-12-08 03:54 UTC by Terminator-J

Updated to match current template, reduced reliance on markdown tricks.

If possible, would love to see how it looks without any additional editing, and/or notes on what syntax to change in my own file revisions to keep Gabriel happy. 😁

2024-12-08 08:33 UTC, gwolf2u requested changes
lots of changes there
remove useless text
don't use ` unless you use it for command with copy option
remove adverts

also did it only for enchilada as fajita is mainly the same and don't want to spend more time seeking all those out

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +  - You need a computer with current AOSP "platform-tools" installed or otherwise on your $PATH (the current official ones from developer.android.com, not some script-kiddie's sketchy all-in-one bund
don't add ` to fastboot command 
will render on new page with copy
for bold and italic (maybe), can use 3x*

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +- crDroid files for your device can be found **[here](https://sourceforge.net/projects/crdroid/files/enchilada/10.x/)**.
link is on download page, so just state that as it was before
there's no need to link it here also since this can change maybe and forget to change here also

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +  - `crDroidAndroid-xxx_boot.img`
don't use ` as that renders as copy command and with - in front, is useless
can use some italic, bold or bold-italic

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +    Download **[MindTheGapps 14.0.0-arm64](https://github.com/MindTheGapps/14.0.0-arm64/releases)**
don't link all the gapps available
should state what you use and test with

also
link is already on download page, gapps button - no need to link here also (just state that)

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
>  - Disable_Dm-Verity_ForceEncrypt:
no need of it as we don't support it anyway

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +**Notice that each command is prefixed with a `./`. This is important. Please keep that prefix when you run each command.**
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +- Step 1: Unzip the `platform-tools-latest-xxx.zip` file you downloaded earlier to any directory you can run programs from.
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +- Step 2: Move the following files into the extracted platform-tools directory (so that they are in the same directory level as the `adb` and `fastboot` executable files), and rename the `.img` files
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +  - `crDroidAndroid-xxx_boot.img` renamed to `boot.img`
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +- Step 3: Open your terminal and `cd` to the extracted platform-tools directory.
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +  - Verify you have correctly installed OnePlus USB drivers by plugging the USB cable back in, and running `fastboot devices` from the terminal window. You should see your device's serial number in t
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +  - Use the volume buttons to page through the boot options until you see `Recovery mode`. Press the power button to select that option.
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +- Step 7: In recovery, choose `Advanced` then `Enter fastboot` to enter fastbootd ("userspace fastboot"), and plug the USB cable back into phone.
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +  - Run `fastboot devices` in terminal to make sure that the userspace fastbootd drivers are working. If not, unplug & re-plug the USB cable again or check for driver updates via Device Manager or Wi
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +  WARNING: If fastboot on the computer returns some error message about not recognizing `wipe-super` or prints a long help message instead, then that means you are either running a very old version o
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +- Step 9: Choose `Enter recovery` on phone to return to recovery, then choose `Apply update` then `Apply from ADB` so that it is waiting to receive an installation package from the computer.
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +  - During a successful sideload, the process will be paused at 47% on the computer, and on the phone you'll be prompted to reboot to recovery again in order to continue flashing Addons (like Google
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +  If you encounter any other installation errors when sideloading besides ROM zip sideloading stopping at 47%, run `./adb pull /tmp/recovery.log` in terminal to get logs to share while asking for hel
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +- Step 11: Back in recovery, choose `Apply update` then `Apply from ADB` again.
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +- Step 13: If you want to run with Google Apps or microG since we don't ship them built-in, now is the time to install. On the phone, choose `Apply update` then `Apply from ADB` again, and from the t
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +- Step 14: Since this is a clean install, navigate back to top level recovery menu on phone, and choose the `Factory reset` option & confirm in order to format the data partition & set up FBE encrypt
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +- Step 15: Choose `Reboot system now` and remember: **𓂀 We love you 3000!**
don't use `- also remove "we love you 3000!" as while I understand why you use it, this is should be written in a pro mode without useless text

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +_Processes addon.d OTA survival scripts, so addons such as Google Apps / microG / Magisk that install survival scripts to `/system/addon.d/` should be preserved automatically_
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +- Step 1: Open `Settings > System > System Updates` on the phone. Before loading an update to install, choose `Preferences` from the menu and turn on the `Prioritize update process` and `Delete updat
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +- Step 2: Now either check for updates, or choose `Local update` from the menu & select the desired ROM zip file from your phone's internal storage. Once the installer has verified the update, choose
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +- Step 3: Reboot once installation has completed. If the screen has turned off or you navigated away from the `System updates` activity to use another app, then the only indication that updating has
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +- Step 2: Reboot phone to recovery and connect USB cable to computer once you're in the crDroid recovery environment. Open a terminal on the computer and run `adb devices` to verify that the phone is
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +- Step 3: On the phone, choose `Apply update` then `Apply from ADB` to begin the phone listening for an update. On the computer, run `./adb sideload path/to/crdroid.zip` (substituting the correct dir
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +- Step 4: On the computer, the process will pause at 47%, and on the phone you'll see it's prompting you to reboot to recovery to install addons (like Google Apps). Choose `Yes` on the phone to reboo
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +- Step 5: If you have any addons to flash (Google Apps, microG, custom kernel zips, etc) now is the time to sideload them. On the phone, choose `Apply update` then `Apply from ADB` to start the phone
don't use `

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +- Step 6: On the phone, choose `Reboot system now` and remember: **𓂀 We love you 3000!**
don't use ` and the 3000

2024-12-08 08:33 UTC, gwolf2u commented on 10/enchilada.md
> +_(Guide adapted with permission from the Evolution-X installation guide originally by jabashque and AnierinBliss, with extensive adaptation & updating over the years by Terminator_J)._
useless text - we don't advertise other roms on crDroid

2024-12-08 17:44 UTC, Terminator-J commented on 10/enchilada.md
> +_(Guide adapted with permission from the Evolution-X installation guide originally by jabashque and AnierinBliss, with extensive adaptation & updating over the years by Terminator_J)._
I'm not advertising other ROMs; I'm giving attribution.

Do you strip out "Copyright 2016, The Android Open Source Project" from the top of license files, or do you add your own line after?

2024-12-08 17:45 UTC, gwolf2u commented on 10/enchilada.md
> +_(Guide adapted with permission from the Evolution-X installation guide originally by jabashque and AnierinBliss, with extensive adaptation & updating over the years by Terminator_J)._
Can leave the name of the author, just don't want other rom name on crDroid site

2024-12-08 18:31 UTC, Terminator-J commented
Thank you for taking time to point out all the formatting and style things you want to see changed; that took a lot of work & time and I respect that.

2024-12-08 20:31 UTC, Terminator-J commented on 10/enchilada.md
> +_(Guide adapted with permission from the Evolution-X installation guide originally by jabashque and AnierinBliss, with extensive adaptation & updating over the years by Terminator_J)._
Okay, so keep the people names and drop the mention of Evo-X by name?

2024-12-08 21:51 UTC, Terminator-J commented
Okay, personally: I hate dry, terse "documentation" that is just a list of steps that doesn't include any explanation or give any options or context or useful examples. That's why I started writing my own guides years ago, before we had "install_docs" available. People liked my guides & explanations on XDA forums. My users like it. It's something I'm very personally invested in, and as I'm sure you understand,... the only way people will keep volunteering for open-source projects is if they're personally invested in it and enjoy doing it.

Obviously you have a different idea of what you want documentation to look like for the official site.
I very much understand adapting the writing to make the site look consistent.

I will rewrite to make it a simple list of steps.

As a compromise, I would like to add a sentence at the end with a link to my XDA posts or GitHub Gists that says something like "For expanded installation guide, optional Google Apps/microG recommendations, and FAQs, click here" or something similar.

Would that be okay?

2024-12-08 22:37 UTC, Terminator-J commented on 10/enchilada.md
> +    Download **[MindTheGapps 14.0.0-arm64](https://github.com/MindTheGapps/14.0.0-arm64/releases)**
I have always maintained a list of known-good Google Apps packages.
I always test both NikGapps "crdroid-official" and MindTheGapps (because it's maintained partially by LineageOS devs and if it isn't working, then that means our *ROM* is broken and should get fixed).
I became a maintainer because I actually wanted to run microG or even vanilla.

So these are all valid options that should work, and users should know that.
I'm open to suggestions for where to put that information so that it's visible, not hidden/buried.

2024-12-08 22:39 UTC, Terminator-J commented on 10/enchilada.md
>  - Disable_Dm-Verity_ForceEncrypt:
People use custom ROMs to be able to root.

It's good to tell users to wait until after first boot to try using Magisk, or flashing my KSU-enabled kernel zip, and has saved me support time to have that sentence there.

2024-12-08 22:42 UTC, Terminator-J commented on 10/enchilada.md
> +**Notice that each command is prefixed with a `./`. This is important. Please keep that prefix when you run each command.**
this is literally what inline code backtick markdown is for.

2024-12-08 22:51 UTC, Terminator-J commented on 10/enchilada.md
> +  - You need a computer with current AOSP "platform-tools" installed or otherwise on your $PATH (the current official ones from developer.android.com, not some script-kiddie's sketchy all-in-one bund
I know it makes it copyable.
Fix the markdown style so it doesn't overlay extra stuff and add to visual clutter; the style is important.

2024-12-08 22:55 UTC, Terminator-J commented on 10/enchilada.md
> +  - `crDroidAndroid-xxx_boot.img`
that's weird, should render as bullet points (unordered list), with inline-code format applied to entry after bullet.

i'll make it dumber.

2024-12-08 23:02 UTC, Terminator-J commented on 10/enchilada.md
> +  - Verify you have correctly installed OnePlus USB drivers by plugging the USB cable back in, and running `fastboot devices` from the terminal window. You should see your device's serial number in t
that's literally the command I want them to be able to copy & paste into the terminal.
this is what the backtick is for.

2024-12-08 23:03 UTC, Terminator-J commented on 10/enchilada.md
> +- Step 3: Open your terminal and `cd` to the extracted platform-tools directory.
fine, i will use a generic verb "navigate" instead of shell command.

2024-12-09 00:13 UTC, Terminator-J commented on 10/enchilada.md
> +  - Run `fastboot devices` in terminal to make sure that the userspace fastbootd drivers are working. If not, unplug & re-plug the USB cable again or check for driver updates via Device Manager or Wi
Again, this is the command I want them to copy & paste, it makes sense to have it inline.
This is what the backtick is for.

2024-12-09 00:25 UTC, Terminator-J commented on 10/enchilada.md
> +- crDroid files for your device can be found **[here](https://sourceforge.net/projects/crdroid/files/enchilada/10.x/)**.
Download page does not have buttons to download all required files, just zip and boot.img.

For first install, users need boot.img, dtbo.img, super_empty.img, vbmeta.img, and the ROM zip as a matched set.
So I'm trying to figure out the best way to quickly link "here's where you can get all the required files" with minimal extra words.

This is a packaging infrastructure issue I'm trying to work around.

Will update instructions to say "Click on 'Download older versions' button on download page to show all files" instead, and remove link.

But that's MORE words, not less. Not as clean. 😅

2024-12-09 00:29 UTC, Terminator-J commented on 10/enchilada.md
> +  If you encounter any other installation errors when sideloading besides ROM zip sideloading stopping at 47%, run `./adb pull /tmp/recovery.log` in terminal to get logs to share while asking for hel
it's a shell command I want users to be able to copy.
that's what the incline code backtick is for.

2024-12-09 00:33 UTC, Terminator-J commented on 10/enchilada.md
> +- Step 15: Choose `Reboot system now` and remember: **𓂀 We love you 3000!**
That message is literally my favorite thing about crDroid.
It has cheered me up over & over again, during some very dark times the last few years.

I would like to keep sharing that with my users, in case it helps some of them.

I will remove it so the official install instructions look more "pro", but I will also ask you to please reconsider in the future.

2024-12-09 00:38 UTC, Terminator-J commented on 10/enchilada.md
> +_Processes addon.d OTA survival scripts, so addons such as Google Apps / microG / Magisk that install survival scripts to `/system/addon.d/` should be preserved automatically_
filenames and paths still seem like useful things to be able to quickly copy/paste, and using the markdown enables that.

i'm changing all of these things that aren't actual shell commands to double quotes instead, to match your preference; but it seems 1) messier, and 2) inelegant in comparison.

If the markdown parser for the crdroid.net site is always adding too much visual decoration when the inline code markdown is used, then that's a problem with the site parsing/styling, not a problem with the markdown being used to enhance readability/function.

can that extra decoration styling be fixed, so we can keep improved function?
much less error-prone than relying on users to be able to only select the text inside pairs of quotes (or some OSes trying to outsmart the user and "smart copy" all the wrong things).

2024-12-09 00:39 UTC, Terminator-J commented on 10/enchilada.md
> +- Step 2: Reboot phone to recovery and connect USB cable to computer once you're in the crDroid recovery environment. Open a terminal on the computer and run `adb devices` to verify that the phone is
it's a shell command I want them to be able to copy.

2024-12-09 00:40 UTC, Terminator-J commented on 10/enchilada.md
> +- Step 3: On the phone, choose `Apply update` then `Apply from ADB` to begin the phone listening for an update. On the computer, run `./adb sideload path/to/crdroid.zip` (substituting the correct dir
Will update menu options with quotes, but keeping shell command as inline code.

2024-12-09 08:03 UTC, gwolf2u commented on 10/enchilada.md
> +  - You need a computer with current AOSP "platform-tools" installed or otherwise on your $PATH (the current official ones from developer.android.com, not some script-kiddie's sketchy all-in-one bund
ok but it will render as copy on new line not as you see on github 
is like command text box with copy button on right

2024-12-09 08:06 UTC, gwolf2u commented on 10/enchilada.md
> +- crDroid files for your device can be found **[here](https://sourceforge.net/projects/crdroid/files/enchilada/10.x/)**.
in this case, link to recovery dir or a different dir and state is not crDroid files needed, but rather specific images
if need to link to crdroid.zip, just state dl page
that's the idea
maybe use a firmware flash script like I do to guacamole/lemonade(p) - see how I did it

2024-12-09 08:07 UTC, gwolf2u commented on 10/enchilada.md
> +    Download **[MindTheGapps 14.0.0-arm64](https://github.com/MindTheGapps/14.0.0-arm64/releases)**
then if you test and support all, I don't mind

2024-12-09 08:08 UTC, gwolf2u commented on 10/enchilada.md
>  - Disable_Dm-Verity_ForceEncrypt:
this was for dm-verity, not for root

2024-12-09 08:09 UTC, gwolf2u commented on 10/enchilada.md
> +- Step 6: On the phone, choose `Reboot system now` and remember: **𓂀 We love you 3000!**
still we do love 3000 ❤️

2024-12-13 03:17 UTC, Terminator-J commented on 10/enchilada.md
>  - Disable_Dm-Verity_ForceEncrypt:
I constantly get asked about it and wanted to specifically say "NO" in advance.

2024-12-13 03:26 UTC, Terminator-J commented
Had to step away for a few days due to unrelated circumstances.

Rewrote to be more "just the pre-installation, first install, and update install steps" and less "start-to-finish guide", according to your notes:
- Removed all inline code markdown, and replaced with either double quotes for filenames/menu option names, or triple-backtick blocks for each terminal command
- Removed lots of other excess markdown to simplify layout/formatting
- Removed lots of extra "commentary" text, moved important notes/warnings to end of each step with consistent label
- Removed many extra links due to old "all in one" guide, directed back to "see ___ button on download page" instead
- Added two external links to streamline "Pre-installation" section instead of trying to solve all possible problems in advance
- Moved attribution line to bottom, removed advertising

Thank you for your patience!

2024-12-14 15:41 UTC, gwolf2u commented
this the final revision?

2024-12-15 17:09 UTC, Terminator-J commented
Okay, should be ready to squash & merge!
Thank you so much for the guidance.

2024-12-15 17:17 UTC, gwolf2u approved these changes

2024-12-15 17:18 UTC, merged